### ISSUE TITLE
 Found ambiguous parameter type [class java.lang.Void] for method match

### ISSUE THREAD

**Issue by qdubious** [spring-cloud-stream-app-starters/python#10]
spring-cloud-starter-stream-processor-python-jython project: 

All three tests contained within class JythonProcessorTests result in

`Caused by: java.lang.IllegalArgumentException: Found ambiguous parameter type [class java.lang.Void] for method match: [public void org.springframework.cloud.stream.app.python.jython.JythonScriptExecutor.afterPropertiesSet() throws java.lang.Exception]`

**Comment by sabbyanandan** [comment]
Hi, @qdubious: What version of the app are you running? If it is from `master`, please switch to [1.0.x branch](https://github.com/spring-cloud-stream-app-starters/python/tree/1.0.x) right away. There's active wip to bring Boot/Cloud 2.0 compatibility on `master`, so it is in an inconsistent state.

**Comment by qdubious** [comment]
I downloaded the following release...

[python-jython-processor-rabbit-1.0.0.RELEASE.jar](
http://repo.spring.io/libs-release/org/springframework/cloud/stream/app/python-jython-processor-rabbit/1.0.0.RELEASE/python-jython-processor-rabbit-1.0.0.RELEASE.jar)

...using the following command...

`java -jar python-jython-processor-rabbit-1.0.0.RELEASE.jar --jython.script=/tmp/test.py`

...which results in the same exception as above.

`2018-02-10 15:12:38.024  INFO 46966 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@39ed3c8d: startup date [Sat Feb 10 15:12:37 EST 2018]; root of context hierarchy
2018-02-10 15:12:38.380  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$aef4d566] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.8.RELEASE)

2018-02-10 15:12:43.758  INFO 46966 --- [           main] r.PythonJythonProcessorRabbitApplication : No active profile set, falling back to default profiles: default
2018-02-10 15:12:43.771  INFO 46966 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@276438c9: startup date [Sat Feb 10 15:12:43 EST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@39ed3c8d
2018-02-10 15:12:44.497  INFO 46966 --- [           main] o.s.i.config.IntegrationRegistrar        : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2018-02-10 15:12:44.950  INFO 46966 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=bc05466f-123d-3bf3-b0a8-99b7419b201f
2018-02-10 15:12:44.964  INFO 46966 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2018-02-10 15:12:44.966  INFO 46966 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2018-02-10 15:12:45.039  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration' of type [org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration$$EnhancerBySpringCGLIB$$59469097] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.116  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration' of type [org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration$$EnhancerBySpringCGLIB$$54a2706e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.163  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$$EnhancerBySpringCGLIB$$93172a5e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.170  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spelConverter' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$SpelConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.180  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cloud.stream.integration-org.springframework.cloud.stream.config.SpringIntegrationProperties' of type [org.springframework.cloud.stream.config.SpringIntegrationProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.245  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [org.springframework.beans.factory.config.PropertiesFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.246  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [java.util.Properties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.277  INFO 46966 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$aef4d566] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-02-10 15:12:45.633  INFO 46966 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2018-02-10 15:12:45.645  INFO 46966 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-02-10 15:12:45.646  INFO 46966 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.23
2018-02-10 15:12:45.749  INFO 46966 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-02-10 15:12:45.749  INFO 46966 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1978 ms
2018-02-10 15:12:46.021  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
2018-02-10 15:12:46.022  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-02-10 15:12:46.022  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-02-10 15:12:46.022  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-02-10 15:12:46.022  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-02-10 15:12:46.023  INFO 46966 --- [ost-startStop-1] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2018-02-10 15:12:46.023  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2018-02-10 15:12:46.023  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
2018-02-10 15:12:46.023  INFO 46966 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2018-02-10 15:12:48.456  WARN 46966 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.app.python.jython.processor.PythonJythonProcessorConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Found ambiguous parameter type [class java.lang.Void] for method match: [public void org.springframework.cloud.stream.app.python.jython.JythonScriptExecutor.afterPropertiesSet() throws java.lang.Exception]
2018-02-10 15:12:48.457  INFO 46966 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-02-10 15:12:48.478  INFO 46966 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-02-10 15:12:48.486 ERROR 46966 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.app.python.jython.processor.PythonJythonProcessorConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Found ambiguous parameter type [class java.lang.Void] for method match: [public void org.springframework.cloud.stream.app.python.jython.JythonScriptExecutor.afterPropertiesSet() throws java.lang.Exception]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.cloud.stream.app.python.jython.processor.rabbit.PythonJythonProcessorRabbitApplication.main(PythonJythonProcessorRabbitApplication.java:29) [classes!/:1.0.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [python-jython-processor-rabbit-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [python-jython-processor-rabbit-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [python-jython-processor-rabbit-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [python-jython-processor-rabbit-1.0.0.RELEASE.jar:1.0.0.RELEASE]
Caused by: java.lang.IllegalArgumentException: Found ambiguous parameter type [class java.lang.Void] for method match: [public void org.springframework.cloud.stream.app.python.jython.JythonScriptExecutor.afterPropertiesSet() throws java.lang.Exception]
	at org.springframework.util.Assert.isNull(Assert.java:113) ~[spring-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.findHandlerMethodsForTarget(MessagingMethodInvokerHelper.java:499) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.<init>(MessagingMethodInvokerHelper.java:226) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.<init>(MessagingMethodInvokerHelper.java:149) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.<init>(MessagingMethodInvokerHelper.java:144) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.<init>(MethodInvokingMessageProcessor.java:60) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.transformer.MethodInvokingTransformer.<init>(MethodInvokingTransformer.java:47) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.config.annotation.TransformerAnnotationPostProcessor.createHandler(TransformerAnnotationPostProcessor.java:59) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.config.annotation.AbstractMethodAnnotationPostProcessor.postProcess(AbstractMethodAnnotationPostProcessor.java:144) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.config.annotation.MessagingAnnotationPostProcessor.processAnnotationTypeOnMethod(MessagingAnnotationPostProcessor.java:228) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.config.annotation.MessagingAnnotationPostProcessor$1.doWith(MessagingAnnotationPostProcessor.java:200) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:530) ~[spring-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:537) ~[spring-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.integration.config.annotation.MessagingAnnotationPostProcessor.postProcessAfterInitialization(MessagingAnnotationPostProcessor.java:180) ~[spring-integration-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	... 23 common frames omitted`

**Comment by artembilan** [comment]
@qdubious ,

Please, find the fix in the #11 .

If you are able to patch existing project with that fix and build target application locally, that would be a solution for your in the version `1.0.0`.

See [Reference Manual](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Celsius.SR1/reference/html/_introduction.html#_using_the_artifacts) for more information.

I think we can backport the fix into the previous version if that is necessary.

Regards

**Comment by qdubious** [comment]
@artembilan - Thanks!  That worked like a charm.  I'm thinking this issue could be closed given it's a duplicate of [#11](https://github.com/spring-cloud-stream-app-starters/python/pull/11)?

**Comment by artembilan** [comment]
Thanks, @qdubious , for the confirmation!

Well, this is issue and that one is pull request. They are connected now and this one will be closed automatically after merging that PR. Unfortunately I don't have permissions to merge it myself even having @dturanski approved it. So, we need to wait for @sabbyanandan who will assign someone to merge the PR or I will be added as a contributor to this project and will be able to merge it and any subsequent 😄

**Comment by sabbyanandan** [comment]
Sorry about that, @artembilan. I fixed your permission - please merge it.
